### ISSUE TITLE
Build error when trying to use local font files

### ISSUE THREAD

**Issue by zackseuberling** [TylorS/snowpack-plugin-hash#10]
While trying to use local font files in my CSS, I run into an UnhandledPromiseRejectionWarning:

```
(node:40405) UnhandledPromiseRejectionWarning: Error: Can't resolve '/fonts/Inter-SemiBold.woff2'
```

My snowpack.config.js file:

```javascript
module.exports = {
  mount: {
    _site: { url: "/", static: true },
    src: "/",
  },
  plugins: [
    "@snowpack/plugin-postcss",
    ["@snowpack/plugin-run-script", { cmd: "eleventy", watch: "$1 --watch" }],
    ["snowpack-plugin-hash"],
  ],
  optimize: {
    bundle: true,
    minify: true,
    target: "es2018",
  },
};
```

My CSS file (using postcss to convert the Tailwind imports):

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url("/fonts/Inter-SemiBold.woff2") format("woff2");
}

@font-face {
  font-family: "Inter";
  font-style: italic;
  font-weight: 600;
  font-display: swap;
  src: url("/fonts/Inter-SemiBoldItalic.woff2") format("woff2");
}
```

When I remove the `@font-face` rules, the build works as expected.

In my specific example, Inter happens to be available via Google Fonts, so adding an additional CSS link rule to the header could resolve it. This isn't always possible or always the ideal webfont loading solution, so I am wondering if there could be a solution for local webfonts.
